apiVersion: v1
kind: Namespace
metadata:
  name: hello-world #создание namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-service-deployment #имя deployment
  namespace: hello-world #указал выше
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-service
  template:
    metadata:
      namespace: hello-world
      labels:
        app: kafka-service #lables важны их можно списком указывать разные
    spec:
      containers:
        - name: kafka-service #присваиваю имя контейнеру в поде
          image: cr.yandex/crpt2j4od8cl0kpuvph9/hello:__VERSION__ #в работе можем менять лишь файл без остановки пода, например на nginx и он будет доступен по этим же портам
          imagePullPolicy: Always
          ports:
            - containerPort: 8182
              #открытый ранее порт контейнера
              #kubectl port-forward (pod-name) 8181(браузер):80(контейнер)
              #Для тех, кто запускает kubectl не у себя, а на удаленном сервере, команда выглядит так:
              #kubectl port-forward --address 0.0.0.0 my-web 8000:80